#!/usr/bin/env python3
"""Split design/Task5_Technical_Design.txt and design/PLEXOS_Pipeline_Build_Backlog.txt into small files Claude Code can load on demand.
Re-run after editing either source file.
Usage: python tools/split_docs.py   (from repo root)"""
import re, pathlib, shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "input_pipeline"
SRC_DESIGN = ROOT / "design" / "Task5_Technical_Design.txt"
SRC_BACKLOG = ROOT / "design" / "PLEXOS_Pipeline_Build_Backlog.txt"

def slug(s, n=40):
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")[:n]

def write(path, lines):
    while lines and lines[-1].strip() in ("", "---"):
        lines = lines[:-1]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

# ---------- design doc: one file per top-level "## N." section ----------
sec_dir = OUT / "design_sections"
shutil.rmtree(sec_dir, ignore_errors=True)
lines = SRC_DESIGN.read_text(encoding="utf-8").splitlines()
blocks, cur, name = [], [], "00_preamble"
for ln in lines:
    m = re.match(r"^## (\d+)\.\s+(.*)", ln)
    if m:
        blocks.append((name, cur)); cur = [ln]
        name = f"{int(m.group(1)):02d}_{slug(m.group(2))}"
    else:
        cur.append(ln)
blocks.append((name, cur))
for name, body in blocks:
    write(sec_dir / f"{name}.md", body)
idx = ["# Design sections", "", "Source of truth: `design/Task5_Technical_Design.txt`. Generated by `tools/split_docs.py`; do not edit these files, edit the source and re-run. Stories cite sections as `§N.N` — open the file for the number's first part (e.g. §7.2.1 -> `07_*.md`).", ""]
idx += [f"- `{n}.md`" for n, _ in blocks]
write(sec_dir / "INDEX.md", idx)

# ---------- backlog ----------
bl = SRC_BACKLOG.read_text(encoding="utf-8").splitlines()
for sub in ("stories", "epics"):
    shutil.rmtree(OUT / sub, ignore_errors=True)
top, epic, story = [], None, None   # each is [key, lines]
out_top, out_epics, out_stories = {}, {}, {}
epic_of = {}
cur_key = ("top", "00_preamble"); cur_lines = []
def flush():
    kind, key = cur_key
    {"top": out_top, "epic": out_epics, "story": out_stories}[kind][key] = cur_lines
for ln in bl:
    m2 = re.match(r"^## (EPIC ([A-J]) — (.*)|(Appendix [AB]) — (.*)|(\d+)\. (.*))", ln)
    m3 = re.match(r"^### ([A-Z]{3,4}-\d+) — (.*)", ln)
    if m2:
        flush(); cur_lines = [ln]
        if m2.group(2):
            cur_key = ("epic", f"{m2.group(2)}_{slug(m2.group(3), 24)}"); epic_of["cur"] = cur_key[1]
        elif m2.group(4):
            cur_key = ("top", f"appendix_{m2.group(4)[-1].lower()}_{slug(m2.group(5), 30)}")
        else:
            cur_key = ("top", f"{int(m2.group(6)):02d}_{slug(m2.group(7), 30)}")
    elif m3:
        flush(); cur_lines = [f"<!-- Epic intro: docs/input_pipeline/epics/{epic_of['cur']}.md -->", ln]
        cur_key = ("story", m3.group(1)); epic_of[m3.group(1)] = epic_of["cur"]
    else:
        cur_lines.append(ln)
flush()
# merge the pre-section-1 preamble + sections 1..5 into one conventions file
conv = []
for k in sorted(out_top):
    if not k.startswith("appendix"):
        conv += out_top[k]
write(OUT / "00_conventions_and_answers.md", conv)
for k, v in out_top.items():
    if k.startswith("appendix"):
        write(OUT / f"{k}.md", v)
for k, v in out_epics.items():
    write(OUT / "epics" / f"{k}.md", v)
for k, v in out_stories.items():
    write(OUT / "stories" / f"{k}.md", v)
print(f"design sections: {len(blocks)}; epics: {len(out_epics)}; stories: {len(out_stories)}")
